/**
 * pending.ts
 *
 * The moderation queue, stored in KV instead of in the public spreadsheet.
 *
 * Why it moved. The map reads a Google Sheet that is shared "anyone with the
 * link can view", and that sharing is document-level: any tab, any `gid`, is
 * readable by anyone, published or not. So while submissions landed in that
 * sheet as `status = "pending"`, the hiding was purely client-side cosmetics —
 * a stranger's name, story, coordinates and photo URL were fetchable the moment
 * they pressed Submit, and stayed fetchable if an officer rejected them. A
 * second "Pending" tab would have changed nothing, because the sheet's sharing,
 * not its publishing, is what exposes it.
 *
 * So unapproved content never enters the sheet now. A submission lives here, in
 * KV, which only the Worker can read. Approving it is what writes a row to the
 * sheet; rejecting it deletes it and its photo. The sheet therefore contains
 * exactly what is already public on the map, and the map's read path stays
 * static and secret-free — no Worker or Apps Script call on the hot path, which
 * is the property that made the original design worth keeping.
 *
 * Keys are `pending:<uuid>` in the SESSION namespace, alongside `admin_session:`
 * and `rl:`. Entries have no TTL: a queue that quietly emptied itself would
 * silently discard submissions, and losing someone's sighting is worse than a
 * queue that needs attention.
 */

// KVNamespace is a global from the wrangler-generated worker-configuration.d.ts.

const PENDING_PREFIX = 'pending:';

export interface PendingSubmission {
  /** Opaque id, also the KV key suffix. Used by the admin UI to address a row. */
  id: string;
  name: string;
  latitude: number;
  longitude: number;
  date: string;
  description: string;
  /** Public /photos/<key> URL, or '' when the submitter attached no photo. */
  photoUrl: string;
  /** R2 object key behind photoUrl, so a rejection can delete the object. */
  photoKey: string;
  placedBy: string;
  /** ISO timestamp of when it was submitted — the queue's sort order. */
  submittedAt: string;
  /**
   * Set when an officer deferred it. Deferred items stay in the queue (they are
   * not public either way) but sort last, so they don't block a fresh review.
   */
  deferred?: boolean;
}

/** Store a submission. Overwrites by id, which only happens on a defer. */
export async function putPending(kv: KVNamespace, item: PendingSubmission): Promise<void> {
  await kv.put(PENDING_PREFIX + item.id, JSON.stringify(item));
}

/** One submission by id, or null if it was already moderated. */
export async function getPending(
  kv: KVNamespace,
  id: string,
): Promise<PendingSubmission | null> {
  if (!isValidId(id)) return null;
  const raw = await kv.get(PENDING_PREFIX + id);
  if (raw === null) return null;
  try {
    return JSON.parse(raw) as PendingSubmission;
  } catch {
    // A corrupt entry should not take down the whole queue listing.
    return null;
  }
}

export async function deletePending(kv: KVNamespace, id: string): Promise<void> {
  if (!isValidId(id)) return;
  await kv.delete(PENDING_PREFIX + id);
}

/**
 * The whole queue, oldest first, with deferred items last.
 *
 * A KV list gives keys only, so each entry costs a read. That is fine at this
 * scale — the queue is a handful of items for a club sticker map — and the
 * 1000-key cap below is a guard against a runaway list, not a paging strategy.
 */
export async function listPending(kv: KVNamespace): Promise<PendingSubmission[]> {
  const { keys } = await kv.list({ prefix: PENDING_PREFIX, limit: 1000 });
  const items = await Promise.all(
    keys.map(async (k) => {
      const raw = await kv.get(k.name);
      if (raw === null) return null;
      try {
        return JSON.parse(raw) as PendingSubmission;
      } catch {
        return null;
      }
    }),
  );
  return items
    .filter((i): i is PendingSubmission => i !== null)
    .sort((a, b) => {
      if (Boolean(a.deferred) !== Boolean(b.deferred)) return a.deferred ? 1 : -1;
      return (a.submittedAt ?? '').localeCompare(b.submittedAt ?? '');
    });
}

/**
 * Ids are generated by crypto.randomUUID, so anything else is a caller error or
 * an attempt to steer the key — checked before it is concatenated into a key.
 */
export function isValidId(id: string): boolean {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(id);
}
